# Name  : Junhong Wang                                                         
# ID    : 504941113                                                            
# Email : oneone@g.ucla.edu

default: dist

dist: my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README
	tar -czvf lab4a-504941113.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README